apiVersion: apps/v1
kind: Deployment
metadata:
  name: lenie-ai-server-deployment
  namespace: lenie-ai-dev
  annotations:
    configmap.reloader.stakater.com/reload: "env-config"
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lenie-ai-server
  template:
    metadata:
      labels:
        app: lenie-ai-server
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: lenie-ai-server
        securityContext:
          allowPrivilegeEscalation: false
        image: lenieai/lenie-ai-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret

        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /startup
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
