---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lenie-ai-db-pvc
  namespace: lenie-ai-dev  # Ta sama przestrzeń nazw co twój ingress
spec:
  accessModes:
    - ReadWriteOnce  # Tryb dostępu typowy dla baz danych
  resources:
    requests:
      storage: 10Gi  # Dostosuj rozmiar według potrzeb
