apiVersion: v1
kind: ConfigMap
metadata:
  name: lenie-ai-server-config
data:
  ENV_DATA: "2025.11.01"
  POSTGRESQL_HOST: "lenie-ai-db-dev.lenie-ai-dev.svc.cluster.local"
  POSTGRESQL_DATABASE: "lenie-ai"
  POSTGRESQL_USER: "postgres"
  POSTGRESQL_PORT: "5432"
  BACKEND_TYPE: "postgresql"
  AWS_REGION: "us-east-1"
  AWS_S3_TRANSCRIPT: "lenie-dev-video-to-text"
  AWS_QUEUE_URL_ADD: "https://sqs.us-east-1.amazonaws.com/008971653395/lenie_websites"
  EMBEDDING_MODEL2: "text-embedding-ada-002"
  EMBEDDING_MODEL: "amazon.titan-embed-text-v1"
  USE_SSL: "false"
  DEBUG: "True"
  PORT: "5000"
  AI_MODEL_SUMMARY: "gpt-4o-2024-05-13"
