apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: {{ .Values.namespace }}
data:
  ENV_DATA: "{{ .Values.envConfig.ENV_DATA }}"
  POSTGRESQL_HOST: "{{ .Values.envConfig.POSTGRESQL_HOST }}"
  POSTGRESQL_DATABASE: "{{ .Values.envConfig.POSTGRESQL_DATABASE }}"
  POSTGRESQL_USER: "{{ .Values.envConfig.POSTGRESQL_USER }}"
  POSTGRESQL_PORT: "{{ .Values.envConfig.POSTGRESQL_PORT }}"
  BACKEND_TYPE: "{{ .Values.envConfig.BACKEND_TYPE }}"
  AWS_REGION: "{{ .Values.envConfig.AWS_REGION }}"
  AWS_S3_TRANSCRIPT: "{{ .Values.envConfig.AWS_S3_TRANSCRIPT }}"
  AWS_QUEUE_URL_ADD: "{{ .Values.envConfig.AWS_QUEUE_URL_ADD }}"
  EMBEDDING_MODEL2: "{{ .Values.envConfig.EMBEDDING_MODEL2 }}"
  EMBEDDING_MODEL: "{{ .Values.envConfig.EMBEDDING_MODEL }}"
  USE_SSL: "{{ .Values.envConfig.USE_SSL }}"
  DEBUG: "{{ .Values.envConfig.DEBUG }}"
  PORT: "{{ .Values.envConfig.PORT }}"
  AI_MODEL_SUMMARY: "{{ .Values.envConfig.AI_MODEL_SUMMARY }}"