apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  POSTGRESQL_PASSWORD: "{{ .Values.POSTGRESQL_PASSWORD }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.AWS_SECRET_ACCESS_KEY }}"
  OPENAI_API_KEY: "{{ .Values.OPENAI_API_KEY }}"
  OPENAI_ORGANIZATION: "{{ .Values.OPENAI_ORGANIZATION }}"
  STALKER_AWS_API_KEY: "{{ .Values.STALKER_AWS_API_KEY }}"
  STALKER_API_KEY: "{{ .Values.STALKER_API_KEY }}"